import React from "react";
import Head from "next/head";
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";

function addPage() {
  return (
    <div>
      <Head>
        <title>Add page | Holidaze</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main></main>
      <Footer />
    </div>
  );
}

export default addPage;
