import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.scss";
import { Tabs } from "@mantine/core";

export default function Admin() {
  return (
    <div>
      <Head>
        <title>Admin | Holidaze</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.admin_container}>
        <div className={styles.admin_action}>
          <h1>Admin</h1>
          <button className={styles.add_button}>Add establishment</button>
        </div>
        <div className={styles.admin_tabs}>
          <Tabs position="apart">
            <Tabs.Tab label="All">First tab content</Tabs.Tab>
            <Tabs.Tab label="Enquiries">Second tab content</Tabs.Tab>
            <Tabs.Tab label="Messages">Third tab content</Tabs.Tab>
          </Tabs>
        </div>
      </main>
      <Footer />
    </div>
  );
}
