import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.scss";
import {
  IoAt,
  IoSunnyOutline,
  IoLocationOutline,
  IoCallOutline,
  IoLogoTwitter,
  IoLogoInstagram,
  IoLogoYoutube,
} from "react-icons/io5";

function contact() {
  return (
    <div className={styles.contact_container}>
      <Head>
        <title>Holidaze | Contact</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.contact_main}>
        <div className={styles.contact_main_info}>
          <h1>Contact us</h1>
          <h4>Leave your email and we will get back to you within 24 hours</h4>
          <div className={styles.info_content}>
            <IoAt />
            <div className={styles.info_content_item}>
              <h5>Email</h5>
              <span>Ask@Holidaze.com</span>
            </div>
          </div>
          <div className={styles.info_content}>
            <IoCallOutline />
            <div className={styles.info_content_item}>
              <h5>Phone</h5>
              <span>+47 335 355 35</span>
            </div>
          </div>
          <div className={styles.info_content}>
            <IoLocationOutline />
            <div className={styles.info_content_item}>
              <h5>Address</h5>
              <span>844 Morris Park avenue</span>
            </div>
          </div>
          <div className={styles.info_content}>
            <IoSunnyOutline />
            <div className={styles.info_content_item}>
              <h5>Working hours</h5>
              <span>8 a.m. – 11 p.m.</span>
            </div>
          </div>
          <div className={styles.info_content_logos}>
            <IoLogoTwitter />
            <IoLogoYoutube />
            <IoLogoInstagram />
          </div>
        </div>
        <div className={styles.contact_main_login}>a</div>
      </main>
      <Footer />
    </div>
  );
}

export default contact;
