import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";

function contact() {
  return (
    <div>
      <Head>
        <title>Holidaze | Contact</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </div>
  );
}

export default contact;
