import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";

function explore() {
  return (
    <div>
      <Head>
        <title>Holidaze | Explore</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main></main>
      <Footer />
    </div>
  );
}

export default explore;
