import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import NavBar from "../components/NavBar";
import SearchBar from "../components/SearchBar";
import styles from "../styles/Home.module.scss";
import { useFormik } from "formik";
import * as yup from "yup";
import "bootstrap/dist/css/bootstrap.min.css";
import axios from "axios";

export async function getStaticProps() {
  try {
    const response = await axios.get("http://localhost:1337/api/hotels");
    const data = await response.data;

    return {
      props: {
        hotels: data.data,
      },
    };
  } catch (error) {
    console.log(error);
  } finally {
  }
}

export default function Home(hotels) {
  try {
    const formik = useFormik({
      initialValues: {
        email: "",
      },
      validationSchema: yup.object({
        email: yup.string().email("Must be a valid email"),
      }),
    });

    return (
      <div className={styles.home_container}>
        <Head>
          <title>Home | Holidaze</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />

        <main className={styles.home_main}>
          <div className={styles.home_heroBanner}>
            <SearchBar />
          </div>
          <div className={styles.home_featuredContent}>
            <h1>Featured hotels</h1>
            <div>
              {hotels.map((hotel) => {
                return <span key={hotel.id}>{hotel.attributes.name}</span>;
              })}
            </div>
          </div>
          <div className={styles.home_emailBanner}>
            <div className={styles.home_emailBanner_leftContent}>
              <h2>Wait a minute...</h2>
              <h3>Subscribe to our newsletter!</h3>
              <p>
                You will never miss important updates, latest news and community
                QA sessions. Our newsletter is once a week, every Sunday.
              </p>
              <div className={styles.emailBanner_action}>
                <form onSubmit={formik.handleSubmit}>
                  <div className={styles.emailBanner_input}>
                    <input
                      type="email"
                      name="email"
                      placeholder="Your email"
                      value={formik.values.email}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                    />
                    {formik.errors.email && (
                      <div className="text-danger">{formik.errors.email}</div>
                    )}
                  </div>
                </form>
                <button type="submit" className={styles.actionButton}>
                  Subscribe
                </button>
              </div>
            </div>
            <div className={styles.home_emailBanner_rightContent}>
              <Image
                src="/images/emailBanner.png"
                height={365}
                width={450}
                alt=""
              />
            </div>
          </div>
        </main>
        <Footer />
      </div>
    );
  } catch (error) {
  } finally {
  }
}
