import React, { useState } from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.scss";
import Image from "next/image";
import { useFormik } from "formik";
import * as yup from "yup";
import "bootstrap/dist/css/bootstrap.min.css";

function loginPage() {
  const [message, setMessage] = useState("");
  const [submitted, setSubmitted] = useState(false);

  const formik = useFormik({
    initialValues: {
      email: "",
      password: "",
    },
    onSubmit: () => {
      setMessage("Message delivered");
      setSubmitted(true);
    },
    validationSchema: yup.object({
      password: yup
        .string()
        .trim()
        .min(2, "Too Short!")
        .max(20, "Too Long!")
        .required("Password is required"),
      email: yup
        .string()
        .email("Must be a valid email")
        .required("Email is required"),
    }),
  });
  return (
    <div className={styles.login_container}>
      <Head>
        <title>Login | Holidaze</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      <main className={styles.login_main}>
        <div className={styles.main_image}>
          <Image
            src="/images/loginImg.png"
            height={500}
            width={500}
            alt="an image of a person and a gigantic phone"
          />
        </div>
        <div className={styles.main_content}>
          <h1>Login</h1>
          <form onSubmit={formik.handleSubmit}>
            <div className="mb-3">
              <label htmlFor="email" className="form-label">
                Email
              </label>
              <input
                type="email"
                name="email"
                className="form-control"
                placeholder="Your@example.com"
                value={formik.values.email}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
              />
              {formik.errors.email && (
                <div className="text-danger">{formik.errors.email}</div>
              )}
            </div>

            <div className="mb-3">
              <label htmlFor="password" className="form-label">
                Password
              </label>
              <input
                type="text"
                name="password"
                className="form-control"
                placeholder=""
                value={formik.values.password}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
              />
              {formik.errors.password && (
                <div className="text-danger">{formik.errors.password}</div>
              )}
            </div>

            <button type="submit" className="btn btn-primary">
              Login
            </button>
          </form>
        </div>
      </main>
      <Footer />
    </div>
  );
}

export default loginPage;
