import React, { useState } from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.scss";
import Image from "next/image";
import { useFormik } from "formik";
import * as Yup from "yup";
import "bootstrap/dist/css/bootstrap.min.css";
import { useRouter } from "next/router";
import { setCookie } from "nookies";
import { Notification } from '@mantine/core';
import { Check } from 'tabler-icons-react';

function LoginPage() {

  const router = useRouter();

  async function handleLogin() {

    try {
      const loginInfo = {
        identifier: values.email,
        password: values.password,
      };

      const login = await fetch("http://localhost:1337/api/auth/local", {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify(loginInfo),
      });
      const loginResponse = await login.json();

      setCookie(null, "jwt", loginResponse.jwt, {
        maxAge: 30 * 24 * 60 * 60,
        path: "/",
      });
      console.log(loginResponse);


      if (login.status === 200) {
        router.push("/admin");
      } 
    } catch (e) {
      console.log(e);
    }
  }

  const {handleSubmit, handleChange, values, touched, errors, handleBlur} = useFormik({
    initialValues: {
      email: "",
      password: "",
    },
    validationSchema: Yup.object({
      email: Yup
      .string()
      .required('Email required')
      .email('Invalid email'),

      password: Yup
      .string()
      .max(9, 'Password must be shorter than 9 characters')
      .min(3, 'Password must be higher than 3 characters')
      .required('Password required'),
    }),
    onSubmit: () => {
      handleLogin()
    }
  })
  

  return (
    <div className={styles.login_container}>
      <Head>
        <title>Sign in | Holidaze</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      <main className={styles.login_main}>
        <div className={styles.main_image}>
          <Image
            src="/images/loginImg.png"
            height={400}
            width={400}
            alt="an image of a person and a gigantic phone"
          />
        </div>
        <div className={styles.main_content}>
          <div className={styles.content_form}>
            <h1>Sign in</h1>
            <form onSubmit={handleSubmit}>
              <div className="mb-3">
                <label htmlFor="email" className="form-label">
                  Email address
                </label>
                <input
                  type="email"
                  name="email"
                  className="form-control"
                  placeholder="admin@admin.com"
                  value={values.email}
                  onChange={handleChange}
                  onBlur={handleBlur}
                />
                {touched.email && errors.email ? (
                  <div className="text-danger">{errors.email}</div>
                ): null}
              </div>

              <div className="mb-3">
                <label htmlFor="password" className="form-label">
                  Password
                </label>
                <input
                  type="password"
                  name="password"
                  className="form-control"
                  placeholder="Pass1234"
                  value={values.password}
                  onChange={handleChange}
                  onBlur={handleBlur}
                />
                {touched.password && errors.password ? (
                  <div className="text-danger">{errors.password}</div>
                ): null}
              </div>

              <button
                type="submit"
                className={styles.login_button}>
                Login
              </button>
            </form>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
export default LoginPage;