import React, { useState } from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.scss";
import Image from "next/image";
import { useFormik } from "formik";
import * as yup from "yup";
import "bootstrap/dist/css/bootstrap.min.css";
import { useRouter } from "next/router";
import { setCookie } from "nookies";

function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const router = useRouter();

  async function handleLogin() {
    try {
      const loginInfo = {
        identifier: email,
        password: password,
      };

      const login = await fetch("http://localhost:1337/api/auth/local", {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify(loginInfo),
      });
      const loginResponse = await login.json();

      setCookie(null, "jwt", loginResponse.jwt, {
        maxAge: 30 * 24 * 60 * 60,
        path: "/",
      });
      console.log(loginResponse);


      if (login.status === 200) {
        router.push("/admin");
      }
    } catch (error) {
      console.log(error);
    }
  }

  const formik = useFormik({
    initialValues: {
      email: "",
      password: "",
    },
    validationSchema: yup.object({
      password: yup
        .string()
        .trim()
        .min(8, "Too Short!")
        .max(9, "Too Long!")
        .required("Password is required"),
      email: yup
        .string()
        .email("Must be a valid email")
        .required("Email is required"),
    }),
  });
  return (
    <div className={styles.login_container}>
      <Head>
        <title>Sign in | Holidaze</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      <main className={styles.login_main}>
        <div className={styles.main_image}>
          <Image
            src="/images/loginImg.png"
            height={400}
            width={400}
            alt="an image of a person and a gigantic phone"
          />
        </div>
        <div className={styles.main_content}>
          <div className={styles.content_form}>
            <h1>Sign in</h1>
            <form onSubmit={formik.handleSubmit}>
              <div className="mb-3">
                <label htmlFor="email" className="form-label">
                  Email address
                </label>
                <input
                  type="email"
                  name="email"
                  className="form-control"
                  placeholder="admin@admin.com"
                  value={email}
                  onChange={(e) => {
                    formik.handleChange, setEmail(e.target.value);
                  }}
                />
                {formik.errors.email && (
                  <div className="text-danger">{formik.errors.email}</div>
                )}
              </div>

              <div className="mb-3">
                <label htmlFor="password" className="form-label">
                  Password
                </label>
                <input
                  type="password"
                  name="password"
                  className="form-control"
                  placeholder="Pass1234"
                  value={password}
                  onChange={(e) => {
                    formik.handleChange, setPassword(e.target.value);
                  }}
                />
                {formik.errors.password && (
                  <div className="text-danger">{formik.errors.password}</div>
                )}
              </div>

              <button
                type="submit"
                className={styles.login_button}
                onClick={() => handleLogin()}
              >
                Login
              </button>
            </form>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

export default LoginPage;
